# Generated by Django 5.2.6 on 2025-09-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=145, null=True)),
                ('father_name', models.CharField(blank=True, max_length=35, null=True)),
                ('birth_year', models.IntegerField()),
                ('birth_date', models.CharField(blank=True, max_length=10, null=True)),
                ('city_name', models.CharField(max_length=22)),
                ('province_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=22, null=True)),
                ('birth_province', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('imputation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('sample_size', models.PositiveIntegerField()),
                ('filled_samples', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=11)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=22, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='core.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateField(auto_now_add=True)),
                ('database_management', models.BooleanField(default=False)),
                ('quota_management', models.BooleanField(default=False)),
                ('collection_management', models.BooleanField(default=False)),
                ('collection_performance', models.BooleanField(default=False)),
                ('telephone_interviewer', models.BooleanField(default=False)),
                ('fieldwork_interviewer', models.BooleanField(default=False)),
                ('focus_group_panel', models.BooleanField(default=False)),
                ('qc_management', models.BooleanField(default=False)),
                ('qc_performance', models.BooleanField(default=False)),
                ('voice_review', models.BooleanField(default=False)),
                ('callback_qc', models.BooleanField(default=False)),
                ('coding', models.BooleanField(default=False)),
                ('statistical_health_check', models.BooleanField(default=False)),
                ('tabulation', models.BooleanField(default=False)),
                ('statistics', models.BooleanField(default=False)),
                ('funnel_analysis', models.BooleanField(default=False)),
                ('conjoint_analysis', models.BooleanField(default=False)),
                ('segmentation_analysis', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=22)),
                ('age_start', models.IntegerField()),
                ('age_end', models.IntegerField()),
                ('target_count', models.PositiveIntegerField()),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'city', 'age_start', 'age_end')},
            },
        ),
    ]
