# Generated by Django 5.2.7 on 2025-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_databaseentry_xlsform"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseentry",
            name="last_manual_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databaseentry",
            name="last_update_requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databaseentry",
            name="update_attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="databaseentry",
            name="update_window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
