# Generated by Django 5.2.8 on 2025-11-10 11:57

from django.conf import settings
from django.db import migrations, models


def set_initial_project_owners(apps, schema_editor):
    Membership = apps.get_model('core', 'Membership')
    Project = apps.get_model('core', 'Project')

    for project in Project.objects.all():
        if Membership.objects.filter(project=project, is_owner=True).exists():
            continue
        membership = (
            Membership.objects.filter(project=project)
            .order_by('start_work', 'pk')
            .first()
        )
        if membership:
            Membership.objects.filter(project=project).update(is_owner=False)
            membership.is_owner = True
            membership.save(update_fields=['is_owner'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_databaseentryeditrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="databaseentryeditrequest",
            new_name="core_databa_entry_i_9ea352_idx",
            old_name="core_editreq_entry_req_idx",
        ),
        migrations.AddField(
            model_name="membership",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="databaseentryeditrequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RunPython(set_initial_project_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_owner", True)),
                fields=("project",),
                name="unique_owner_per_project",
            ),
        ),
    ]
