# Generated by Django 5.2.8 on 2025-11-14 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("membership_added", "Membership Added"),
                    ("project_started", "Project Started"),
                    ("project_deadline", "Project Deadline"),
                    ("custom_message", "Custom Message"),
                    ("event_invite", "Event Invitation"),
                    ("event_update", "Event Updated"),
                    ("event_reminder", "Event Reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "reminder_minutes_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
    ]
