# Generated by Django 5.2.8 on 2025-11-14 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_notification_event_type_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sample_source",
            field=models.CharField(
                choices=[("database", "Respondent Bank"), ("upload", "Excel Upload")],
                default="database",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sample_upload",
            field=models.FileField(blank=True, null=True, upload_to="project_samples/"),
        ),
        migrations.AddField(
            model_name="project",
            name="sample_upload_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="sample_upload_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UploadedSampleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(max_length=32)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_from_row",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assigned_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_samples",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "completed"],
                        name="core_upload_project_226d15_idx",
                    ),
                    models.Index(
                        fields=["project", "assigned_to"],
                        name="core_upload_project_2faec6_idx",
                    ),
                ],
                "unique_together": {("project", "phone")},
            },
        ),
    ]
