# Generated by Django 5.2.8 on 2025-11-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_project_call_result_metadata_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quota",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="person",
            name="birth_city",
        ),
        migrations.RemoveField(
            model_name="person",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="birth_province",
        ),
        migrations.RemoveField(
            model_name="person",
            name="father_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="imputation",
        ),
        migrations.RemoveField(
            model_name="person",
            name="province_name",
        ),
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quota",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="city_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="quota",
            name="age_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quota",
            name="age_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quota",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="quota",
            constraint=models.UniqueConstraint(
                fields=("project", "city", "age_start", "age_end", "gender"),
                name="unique_quota_dimension",
            ),
        ),
    ]
