# Generated by Django 5.2.8 on 2025-11-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_quota_unique_together_remove_person_birth_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="edit_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="product_matrix_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="review_data",
            field=models.BooleanField(default=False),
        ),
    ]
