# Generated by Django 5.2.9 on 2025-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_reviewrow_review_started_at_reviewrow_review_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="sample_size_calculator",
            field=models.BooleanField(default=False),
        ),
    ]
