# Generated by Django 5.2.9 on 2025-12-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_membership_sample_size_calculator"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseentry",
            name="source_type",
            field=models.CharField(
                choices=[("kobo", "Surveyzen / Kobo"), ("upload", "Uploaded file")],
                default="kobo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="databaseentry",
            name="upload_file",
            field=models.FileField(
                blank=True, null=True, upload_to="database_uploads/"
            ),
        ),
        migrations.AddField(
            model_name="databaseentry",
            name="upload_sheet_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="databaseentry",
            name="asset_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="databaseentry",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
