# Generated by Django 6.0 on 2025-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_databaseentry_postgres_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="survey_link",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Survey Link"
            ),
        ),
        migrations.AlterField(
            model_name="databaseentry",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("kobo", "Surveyzen / Kobo"),
                    ("upload", "Uploaded file"),
                    ("postgres", "PostgreSQL"),
                ],
                default="kobo",
                max_length=20,
            ),
        ),
    ]
